
name: Python unittests
on: [push, workflow_dispatch]
jobs:
  Python-Tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python install
      uses: actions/setup-python@v4
      with: 
        python-version: 3.12
    
    - name: Install Python dependencies

    - name: Run tests
      run: python -m unittest discover -p *_test.py
